services:
  app:
    build:
      context: .
      args:
        NODE_ENV: ${NODE_ENV:-production}
        DB_CONNECTION: ${DB_CONNECTION:-mysql2}
        DB_HOST: ${DB_HOST:-mysql2}
        DB_PORT: ${DB_PORT:-3306}
        DB_DATABASE: ${DB_DATABASE:-database}
    ports:
      - "3333:3333"
    environment:
      - NODE_ENV
      - DB_CONNECTION
      - DB_HOST
      - DB_PORT
      - DB_DATABASE
    depends_on:
      - mysql2
      - redis
    restart: always

  mysql2:
    image: mysql:8.0
    container_name: mysql2
    restart: unless-stopped
    ports:
      - ${DB_PORT:-3306}:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-database}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-1234}
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - ${REDIS_PORT:-6379}:6379
    networks:
      - laravel


  server2:
    image: nginx:stable-alpine
    container_name: server2
    restart: unless-stopped
    ports:
      - ${WEB_PORT:-80}:80
    volumes:
      - ./:/var/www
      - ./ngnix:/etc/nginx/conf.d/
    depends_on:
      - app
    networks:
      - laravel

volumes:
  dbdata:
networks:
  laravel:
    driver: bridge
